baseurl = "/"
publishDir = "docs"
title = "Jeffrey W. Hollister"
author = "Jeff Hollister"
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"

googleAnalytics = ""
disqusShortname = "jeffreywhollister"
disable_mathjax = false

pygmentsstyle      = "vs"
pygmentscodefences = true


ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  sitename = "Jeffrey W. Hollister"
  
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Vitae"
    url = "/cv/"
    weight = 3
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/jhollist"
    weight = 4
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/jhollist"
    weight = 5
[[menu.main]]
    name = "Scholar"
    url = "https://scholar.google.com/citations?user=Fn9BjfIAAAAJ&hl=en"
    weight = 6
[[menu.main]]
    name = "ORCID"
    url = "https://orcid.org/0000-0002-9254-9740"
    weight = 7

