---
output: 
  word_document:
    reference_doc: resume_template.docx
---

# Summary
I am an ecologist and data scientist with expertise in the spatial component of ecology and environmental sciences.  The focus of my work is lakes, landscapes, R, and GIS and a unifying theme to my research is using Open Science (Open Access, Open Source, and Open Data) and data science to benefit environmental and ecological research.

# Core Competencies

## Data Science
One of my primary areas of expertise is in the full data analysis workflow.  I primarily use R to harvest, manage, and manipulate data so that I may analyze and visualize those data to answer a variety of ecological and environmental questions.  I have experience working with databases, a variety of statistical and machine learning approaches, and static and interactive data visualization. 

## Geospatial technologies
Nearly all my research and project work contains a geospatial focus.  As such I have gained decades of experience using geospatial tools, including the Esri suite of tools and, more recently, the open source stack supported by the Open Source Geospatial Foundation and the Open Geospatial Consortium. 

## Ecology
My graduate education and subsequent research have focused on landscape ecology and how spatial patterns affect water quality in fresh- and salt-water systems.  I have experience collecting terrestrial and limnological data, analyzing that data, and publishing my results as evidenced by more than 30 peer reviewed publications, chapters, and non-peer reviewed articles.  

## Collaboration
A hallmark of my career has been working with a broad array of individuals and groups within the US EPA, including Office of Research and Development, Office of Environmental Information, and several Regions.  In addition I have strong working relationships at the University of Rhode Island and with several other outside entities such as through my work with [The Carpentries](https://carpentries.org/) as an instructor and member of the Geospatial Curriculum Advisory Committee.

## Teaching
Over the last several years, I have devoted significant time to teaching others how to use R.  Since 2013 I have led more than 20 separate R and Open Science workshops to audiences in US EPA, the University of Rhode Island, various scientific societies, and other outside entities.

# Skills and tools

- R: 15+ years as a useR!, developed packages, maintained RStudio and Shiny servers, `tidyverse` acolyte
- GIS: Open Source Geospatial Foundation Geospatial Stack (as implemented across many R packages), and Esri tool set.
- Visualization: Primarily via `ggplot2`, but some experience with javascript libraries as implemented in R.
- Data: SQL, tidy data design from environmental monitoring, management with `dplyr` and `tidyr`
- Miscellany: Just enough HTML, CSS, and Javascript

# Experience

- **Aug 2008 - Present**, Research Ecologist, U.S. Environmental Protection Agency, Atlantic Ecology Division, Narragansett, RI

I serve as principle investigator and provide leadership to the division on research in harmful algal blooms in lakes and on the use of data science tools in environmental research. I currently serve as a co-Lead on a project exploring cyanobacteria risk in lakes of the Northeastern US.

- **May 2006 – July 2008**, Postdoctoral Landscape Ecologist, U.S. Environmental Protection Agency, Atlantic Ecology Division, Narragansett, RI

I developed statistical and modeling tools (e.g. Conditional Probability Analysis with R and Excel) to facilitate use of defensible techniques in water quality criteria development. Provided Landscape Ecology, Spatial Statistics and GIS support to a variety of ongoing projects. Explored linkages between landscape and downstream receiving waters and examined utility of broad scale monitoring data in identifying and assessing ecological impairment.

- **Aug 2005 – May 2006**, Postdoctoral Fellow, U.S. Coast Guard Academy, Department. of Science, Marine Sciences Section, New London, CT

Continued prior research on multi-scale interactions between landscape structure and sediment metal concentrations and predictive modeling of estuarine impairment. Worked with students, faculty and colleagues in the Marine Sciences Section, the International Ice Patrol, and Information Services Division on a wide variety of Geographic Information Systems projects. Taught a general education Oceanography course and GIS lab.

- **Jan 2005 – July 2005**, Postdoctoral Associate, American Institute of Biological Sciences, National Ecological Observatory (NEON) Project Office, Washington, DC

Facilitated and assisted with the planning of the first national ecological observatory for the United States, NEON. Initiated the NEON Project Office first Geographic Information Systems, maintained the NEON web presence, and interacted with research scientists and educators on the NEON Senior Management Team and National Network Design Committee.

- **June 1998 – July 2000**, Lead Research Technician in Landscape Ecology, J.W. Jones Ecological Research Center, Landscape Ecology Lab, Newton, GA

Conducted research on ecological impacts of small wetland loss in the Southeastern United States, use of home range in the design of gopher tortoise (Gopherus polyphemus) reserves, and habitat use and landscape ecology of Northern Bobwhite Quail . Other research duties included remote sensing data analysis, GIS analysis, and field data collection.  Managed day-to-day operations of the Landscape Ecology Lab.

- **Aug 1997 – Jan 1998**, Geographic Information Systems Specialist, Research Triangle Institute, Research Triangle Park, NC
  
Developed a GIS methodology and series of Arc Macro Language scripts to facilitate the identification of river reaches, as required by the Clean Water Act, in the states of North Dakota and Arkansas.

# Education

- **2004**, Doctor of Philosophy in Environmental Science, Department of Natural Resources Science, University of Rhode Island, Kingston, RI
- **1997**, Masters of Environmental Management, Nicholas School of the Environment, Duke University, Durham, NC
- **1995**, Bachelor of Science in Biology, Magna Cum Laude, Baker University, Baldwin City, KS

# Selected Projects

- Responsible for data management, analysis, and visualization on [Raposa *et al.* (2018)](https://doi.org/10.7717/peerj.4876) and designed the [correlation matrix visualizations](https://doi.org/10.7717/peerj.4876/fig-4) with inspiration from several different types of heat maps. Details available in <https://github.com/jhollist/crabs>.
- Designed and developed the `quickmapr` package which provides interactive tools for spatial data in R.  Latest release on CRAN in June 2018
- Designed and developed the `lakemorpho` package which provides tools to calculate a suite of common morphometry metrics commonly used in the study of lakes.  Latest release on CRAN in February 2018
- Designed and developed the `elevatr` package.  This package access several APIs to facilitate the use of Digital Elevation Model data in R.  Latest release on CRAN in January 2018.



