---
title: 'What goes up, must Blogdown:  Version 3 (or 4) of jwhollister.com'
author: Jeffrey Hollister
date: '2018-06-16'
slug: what-goes-up-must-blogdown-version-3-or-4-of-jwhollister-com
categories:
  - R
  - Site-Details
tags:
  - blogdown
  - website
---

So, I finally have my website up and running as a Blogdown/Hugo site.  I have been meaning to make this switch for some time now, but never really found the time until recently.  Writing up the gory details of my experience doesn't seem like a good use of my time (nor your time to read it).  This is because it wasn't very difficult a process and many others have taken the time to put together really nice documentation.  So, I'll just link to the sites I used and say a word or two about the theme I used.

First, here are the links I found to be best: 

- [Blogdown Book](https://bookdown.org/yihui/blogdown/)
- [Up and Running with Blogdown - Allison Presmanes Hill](https://alison.rbind.io/post/up-and-running-with-blogdown/)
- [Hugo Documentation](https://gohugo.io/documentation/)

Second, I struggled picking a theme.  I didn't want one that was too fancy, but many of the simple themes had things missing that I wanted.  In the end, I chose one of the nicest (IMO) of the clean themes, Nan Xiao's [Tanka](https://github.com/road2stat/hugo-tanka). I made a few small tweaks for my purposes. First, I wanted to be able to create some stand alone pages that would have dates listed on them or get added to the blog listing on the main page. Second, I made a few tweaks to colors, and Last, I add some fanciness with the Font Awesome icons on the menus.

All in all, an improvement over my old site and now I can be like the cool kids.
