---
title: My project management workflow, or, how I make the most of limited mental bandwidth
author: Jeffrey Hollister
draft: true
date: '2018-06-20'
categories:
  - R
tags:
  - github
  - projects
  - RStudio
---

Several weeks ago, there was some activity on Twitter espousing the virtues RStudio projects, including a mention of Jenny Bryan's post on [Project-oriented workflow](https://www.tidyverse.org/articles/2017/12/workflow-vs-script/)  Reading through the tweets and re-reading Jenny's post reminded me that even though many of us use Projects or other tools to organize our work, the specifics of our toolset and workflows are still likely unique and reflect a lot of personal decisions and preferences.  The other thing that struck me is that aside from Jenny's post, I have rarely seen these types of things documented (they may be, I just blissfully unaware).  If they were documented, we could possibly learn from each others practices.  So, in this post I lay out the workflow I use in case others might find something useful in it.  I would also be interested in hearing how others organize their own work, so please do comment below with your own ideas.

# My take on "Project oriented workflow"
Do what Jenny said.  In other words, the purpose of this post are to talk about issues outside of what was in Jenny's post.

# Flat folder structure: `projects/`

# RStudio all the things

# GitHub as the hub
https://jenthompson.me/2018/06/23/work-online-cautionary/

I find that min case the workflow I have developed over the years